### ISSUE TITLE
Reduce memory usage?

### ISSUE THREAD

**Issue by gabrielwhite** [Erikvl87/docker-languagetool#105]
Is there a way to reduce memory usage and retain performance (single user instance)?

I'm sitting on 413MB without doing anything.

```
services:
  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool
    restart: unless-stopped
    ports:
        - 8010:8010
    environment:
        - langtool_languageModel=/ngrams
#        - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
#        - Java_Xmx=1024m  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
        - ./data:/ngrams
```
