### ISSUE TITLE
502 with high request rate

### ISSUE THREAD

**Issue by calumgoodchild** [Erikvl87/docker-languagetool#4]
We are sending a large number of requests per second to this server and receiving a lot of 502 errors. The server itself doesn't log any errors. We are running this with 128 threads, pipeline cache is enabled. I have tried increasing all the timeouts to no avail.

Ideally we want to send around 1000 rps, but regardless of server resource, the server doesn't seem to be able to handle any more than 300/s.

It looks like the connection is prematurely closing. Any help would be appreciated.

**Comment by Erikvl87** [comment]
I haven't had the time yet to create a proper reproduceable case, but I guess the HTTP 502 response is coming from the LanguageTool HTTPServer. If you agree with that I would advice you to open up an issue at the official LanguageTool repository first: https://github.com/languagetool-org/languagetool/issues

I am not sure about your setup but have you looked at configuring a load balancer, e.g. using [Docker Swarm](https://docs.docker.com/engine/swarm/)?

**Comment by calumgoodchild** [comment]
Strange, because I've tested it behind an nginx load balancer with multiple containers but the rps does not increase. It's not nginx throttling the requests because I've also tested direct to the container. 

I'll open a ticked on the LanguageTool repo.

Cheers for coming back.

**Comment by Erikvl87** [comment]
If I have time next weekend I'll try to reproduce to check if it has something to do with the Dockerfile or with LanguageTool itself. If you happen to have some easy steps to reproduce, please add them in both this ticket and the one you are creating in the LanguageTool repo.

**Comment by Erikvl87** [comment]
Did you find the cause of the HTTP 502 errors? I did a small test with the configuration below, but sending out lots of requests did not result in HTTP 502 errors. 

I did had the same issue as you where scaling the app (on the same machine) didn't increase the RPM but that could be due to network-, memory- or CPU limitations or improper LanguageTool configuration (I have been playing with the settings `pipelinePrewarming`, `pipelineCaching` and `maxCheckThreads` and memory settings with little or no avail). Nor do I know if running multiple virtual images on the same physical machine should increase the RPM or that a single instance with different configuration would be more appropriate. I think those are great questions to ask at the official LanguageTool repository. Did you by any chance already opened up a ticket there?

My tests were on a laptop (Intel® Core™ i7-10710U with 16GB ram) running Docker on Windows 10 using the WSL 2 based engine.


**docker-compose.yml**
```yml
version: "3.8"

services: 
    langtool:
        image: erikvl87/languagetool
        environment:
            - langtool_pipelinePrewarming=true
            - langtool_pipelineCaching=true
            - Java_Xms=2g
            - Java_Xmx=2g
        networks: 
            - "langtool_net"

    ngnix:
        image: nginx:1.19.1
        ports: 
            - "8080:80"
        volumes: 
            - './nginx.conf:/etc/nginx/nginx.conf:ro'
        networks: 
            - "langtool_net"
        depends_on: 
            - langtool

networks: 
    langtool_net:
```

**nginx.config**
```
events {
  worker_connections 4096;  ## Default: 1024
}

http {
    upstream app {
        server langtool:8010; ## Docker will redistribute the requests over the scale set
    }

    server {
        listen 80;

        location / {
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://app;
        }
    }
}
```

startup cmd: `docker-compose up --scale langtool=3`
