### ISSUE TITLE
Running as https, under nginx or custom domain

### ISSUE THREAD

**Issue by AlessioGr** [Erikvl87/docker-languagetool#43]
Hey,

how can I run this with https enabled, either via nginx or a custom domain? I found no information regarding this in the readme.

Do I need to change the Dockerfile to use the nginx alpine image? And what would I do next?

**Comment by VincentSC** [comment]
Via nginx-proxy.

Here's the docker-compose:

```
version: "3"

services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
#    ports:
#      - 8010:8010
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8010
      - LETSENCRYPT_HOST=${DOMAIN}
      - langtool_languageModel=/ngrams
      - Java_Xms=512m
      - Java_Xmx=1g
    volumes:
      - ./volumes/ngrams:/ngrams
```

Set the domain in `.env`.
