### ISSUE TITLE
Error: codec footer mismatch

### ISSUE THREAD

**Issue by arladmin** [Erikvl87/docker-languagetool#58]
I'm running the provided docker-compose.yml file on my local system, with downloaded n-grams dataset.

```
---

version: "3"

services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
      - 8710:8010                        # Using default port from the image
    environment:
      - langtool_languageModel=/ngrams   # OPTIONAL: Using ngrams data
      - Java_Xms=2g                    # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=4g                      # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - ./ngrams:/ngrams     # OPTIONAL: The location of ngrams data on the local machine

```

When trying out an API call to the `check` endpoint, i'm seeing the below given error.
API call:
```
curl --location --request POST 'http://192.168.1.242:8710/v2/check' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'text=<my text data>' \
--data-urlencode 'language=en-GB'
```

Error->

```
Error: Internal Error: java.lang.RuntimeException: org.apache.lucene.index.CorruptIndexException: codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=MMapIndexInput(path="/ngrams/en/3grams/_1e4_Lucene50_0.tim")), detected: en-US
```

Could use some guidance regarding diagnosing and resolving this issue.

Thanks.
