### ISSUE TITLE
After the latest update the container throws an error and stops

### ISSUE THREAD

**Issue by ovizii** [Erikvl87/docker-languagetool#60]
Here is the relvant line from the logs:

`languagetool  | Caused by: java.lang.UnsatisfiedLinkError: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/languagetool/.cache/JNA/temp/jna8961190279417234313.tmp)`

Any more info I can supply? 

II've been happily using your image for a couple of months and have set it to auto-update via watchtower so I know it stopped working after the last update.

**Comment by ovizii** [comment]
Switching from the latest tag to 5.9 everything works again.

` image: erikvl87/languagetool:5.9 `

**Comment by Erikvl87** [comment]
Thanks for reporting! Could you let me know on what architecture you are running the container? And what are the reproduction steps?

**Comment by ovizii** [comment]
Hey, thanks, that was fast. I run this on a small home server:

```
uname -m
x86_64
```

here is my docker-compose.yml comments and all:

```
version: "3.8"                                                                                                                                                  
                                                                                                                                                                
# https://github.com/Erikvl87/docker-languagetool                                                                                                               
# env variables from here https://languagetool.org/development/api/org/languagetool/server/HTTPServerConfig.html                                                
# prefixed with langtool_                                                                                                                                       
                                                                                                                                                                
services:                                                                                                                                                       
  languagetool:                                                                                                                                                 
#    image: erikvl87/languagetool:latest                                                                                                                        
    image: erikvl87/languagetool:5.9                                                                                                                            
    container_name: languagetool                                                                                                                                
    hostname: languagetool                                                                                                                                      
    restart: "no"                                                                                                                                               
    environment:                                                                                                                                                
      - TZ=Europe/Berlin                                                                                                                                        
      - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data                                                                                           
      - langtool_pipelinePrewarming=true                                                                                                                        
      - langtool_pipelineCaching=true                                                                                                                           
      - langtool_maxCheckThreads=2 # 10 are default                                                                                                             
      - Java_Xms=256m  # OPTIONAL: Setting a minimal Java heap size of 256 mib                                                                                  
      - Java_Xmx=2g  # OPTIONAL: Setting a maximum Java heap size of 1 Gib                                                                                      
    networks:                                                                                                                                                   
      - traefik                                                                                                                                                 
    labels:                                                                                                                                                     
      - "traefik.enable=true"                                                                                                                                   
      - "traefik.docker.network=traefik"                                                                                                                        
      - "traefik.http.routers.languagetool.tls=true"                                                                                                            
      - "traefik.http.routers.languagetool.entrypoints=websecure"                                                                                               
      - "traefik.http.routers.languagetool.rule=Host(`sub.mydomain.tld`)"                                                                                         
      - "traefik.http.routers.languagetool.middlewares=secHeaders@file"                                                                                         
      - "traefik.http.routers.languagetool.service=languagetool"                                                                                                
      - "traefik.http.services.languagetool.loadbalancer.server.port=8010"                                                                                      
    volumes:                                                                                                                                                    
      - /opt/languagetool/ngrams:/ngrams                                                                                                                        
      - /dev/shm:/tmp                                                                                                                                           
                                                                                                                                                                
                                                                                                                                                                
networks:                                                                                                                                                       
  traefik:                                                                                                                                                      
    external: true                                                                                                                                              
    name: traefik
```

Regarding reproduction steps, no idea, unless you also use traefik. In that case simply replace sub.mydomain.tld with a domain hosted by your traefik reverse proxy. The above version (using: latest) was in use ever since I found your image. It has been automatically updated by watchtower but like I said, 5.9 is the latest that works. 

Maybe you can spot a problem in my compose file?
