### ISSUE TITLE
Random occurrences of wrong language

### ISSUE THREAD

**Issue by truthsword** [Erikvl87/docker-languagetool#61]
Running the latest docker on Debian. Language set to English. 95% of the time the spell checker works as expected, but occasionally it indicates correctly spelled words for correction, and offers Italian choices.

Generally this reverts to English after a page refresh. Frequency is multiple times a week.

Here's my docker compose:
```
version: "3"
services:
  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=512m
      - Java_Xmx=1g
    networks:
      - languagetool_default
    ports:
      - 8010:8010
    restart: unless-stopped
    user: languagetool
    volumes:
      - /home/user1/docker/languagetool/ngrams:/ngrams
networks:
  languagetool_default:
    name: languagetool
```
Any suggestions?
