### ISSUE TITLE
Docker image crashing with JRE fatal error

### ISSUE THREAD

**Issue by gabrielwhite** [Erikvl87/docker-languagetool#91]
I've been running this docker image without a problem for more than a year. It's now crashing on startup. I'm running it inside a Debian 12 LXC on Proxmox (no changes to this setup). I tried starting with a clean setup, and still the same error.

Not sure whether there's any more info I can provide that will help.

docker-compose.yaml

```
services:
  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool
    restart: unless-stopped
    ports:
        - 8010:8010
    environment:
        - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
        - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
        - Java_Xmx=1024m  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
        - ./data:/ngrams
```

console:

```
Attaching to languagetool
languagetool  | The following configuration is passed to LanguageTool:
languagetool  | languageModel=/ngrams
languagetool  | 2024-04-01 21:39:17.328 GMT INFO  org.languagetool.server.DatabaseAccessOpenSource Not setting up database access, dbDriver is not configured
languagetool  | 2024-04-01 21:39:17 +0000 WARNING: running in HTTP mode, consider running LanguageTool behind a reverse proxy that takes care of encryption (HTTPS)
languagetool  | 2024-04-01 21:39:17 +0000 WARNING: running in public mode, LanguageTool API can be accessed without restrictions!
languagetool  | 2024-04-01 21:39:17 +0000 Setting up thread pool with 10 threads
languagetool  | #
languagetool  | # A fatal error has been detected by the Java Runtime Environment:
languagetool  | #
languagetool  | #  SIGSEGV (0xb) at pc=0x0000771a447959ce (sent by kill), pid=1, tid=9
languagetool  | #
languagetool  | # JRE version: OpenJDK Runtime Environment (11.0.21+9) (build 11.0.21+9-alpine-r0)
languagetool  | # Java VM: OpenJDK 64-Bit Server VM (11.0.21+9-alpine-r0, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
languagetool  | # Problematic frame:
languagetool  | # J 875 c1 java.util.regex.Pattern.peek()I java.base@11.0.21 (26 bytes) @ 0x0000771a447959ce [0x0000771a44795860+0x000000000000016e]
languagetool  | #
languagetool  | # Core dump will be written. Default location: /LanguageTool/core
languagetool  | #
languagetool  | # An error report file with more information is saved as:
languagetool  | # /LanguageTool/hs_err_pid1.log
languagetool  | Compiled method (c1)     430  875       3       java.util.regex.Pattern::peek (26 bytes)
languagetool  |  total in heap  [0x0000771a44795690,0x0000771a44795ba8] = 1304
languagetool  |  relocation     [0x0000771a44795808,0x0000771a44795850] = 72
languagetool  |  main code      [0x0000771a44795860,0x0000771a44795a80] = 544
languagetool  |  stub code      [0x0000771a44795a80,0x0000771a44795ac0] = 64
languagetool  |  metadata       [0x0000771a44795ac0,0x0000771a44795ad0] = 16
languagetool  |  scopes data    [0x0000771a44795ad0,0x0000771a44795b08] = 56
languagetool  |  scopes pcs     [0x0000771a44795b08,0x0000771a44795b88] = 128
languagetool  |  dependencies   [0x0000771a44795b88,0x0000771a44795b90] = 8
languagetool  |  nul chk table  [0x0000771a44795b90,0x0000771a44795ba8] = 24
languagetool  | Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
languagetool  | #
languagetool  | # If you would like to submit a bug report, please visit:
languagetool  | #   https://gitlab.alpinelinux.org/alpine/aports/issues
languagetool  | #
languagetool exited with code 0
```
